name: Update Tags

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse semver
        uses: madhead/semver-utils@v4
        id: version
        with:
          version: ${{ github.ref_name }}

      - name: Update tags
        run: |
          TAGS='v${{ steps.version.outputs.major }} v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}'

          echo ${{ github.ref_name }}
          
          for t in $TAGS; do
            echo $t
            #git tag -f "$t"
            #git push origin ":$t" 2>/dev/null || true
            #git push origin "$t"
          done
